/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsuariosRouteImport } from './routes/_auth/usuarios'
import { Route as AuthTrasladosRouteImport } from './routes/_auth/traslados'
import { Route as AuthPanaderiaRouteImport } from './routes/_auth/panaderia'
import { Route as AuthNominaRouteImport } from './routes/_auth/nomina'
import { Route as AuthMiNominaRouteImport } from './routes/_auth/mi-nomina'
import { Route as AuthMesasRouteImport } from './routes/_auth/mesas'
import { Route as AuthInventarioRouteImport } from './routes/_auth/inventario'
import { Route as AuthImpresorasRouteImport } from './routes/_auth/impresoras'
import { Route as AuthCuentasPorPagarRouteImport } from './routes/_auth/cuentas-por-pagar'
import { Route as AuthCatalogoRouteImport } from './routes/_auth/catalogo'
import { Route as AuthCajaRouteImport } from './routes/_auth/caja'
import { Route as AuthPedidosIdPedidoRouteImport } from './routes/_auth/pedidos.$idPedido'
import { Route as AuthEmpleadosIdRouteImport } from './routes/_auth/empleados.$id'
import { Route as AuthCobroIdPedidoRouteImport } from './routes/_auth/cobro.$idPedido'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsuariosRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrasladosRoute = AuthTrasladosRouteImport.update({
  id: '/traslados',
  path: '/traslados',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPanaderiaRoute = AuthPanaderiaRouteImport.update({
  id: '/panaderia',
  path: '/panaderia',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNominaRoute = AuthNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMiNominaRoute = AuthMiNominaRouteImport.update({
  id: '/mi-nomina',
  path: '/mi-nomina',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMesasRoute = AuthMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventarioRoute = AuthInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImpresorasRoute = AuthImpresorasRouteImport.update({
  id: '/impresoras',
  path: '/impresoras',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCuentasPorPagarRoute = AuthCuentasPorPagarRouteImport.update({
  id: '/cuentas-por-pagar',
  path: '/cuentas-por-pagar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCatalogoRoute = AuthCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCajaRoute = AuthCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPedidosIdPedidoRoute = AuthPedidosIdPedidoRouteImport.update({
  id: '/pedidos/$idPedido',
  path: '/pedidos/$idPedido',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmpleadosIdRoute = AuthEmpleadosIdRouteImport.update({
  id: '/empleados/$id',
  path: '/empleados/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCobroIdPedidoRoute = AuthCobroIdPedidoRouteImport.update({
  id: '/cobro/$idPedido',
  path: '/cobro/$idPedido',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/caja': typeof AuthCajaRoute
  '/catalogo': typeof AuthCatalogoRoute
  '/cuentas-por-pagar': typeof AuthCuentasPorPagarRoute
  '/impresoras': typeof AuthImpresorasRoute
  '/inventario': typeof AuthInventarioRoute
  '/mesas': typeof AuthMesasRoute
  '/mi-nomina': typeof AuthMiNominaRoute
  '/nomina': typeof AuthNominaRoute
  '/panaderia': typeof AuthPanaderiaRoute
  '/traslados': typeof AuthTrasladosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/cobro/$idPedido': typeof AuthCobroIdPedidoRoute
  '/empleados/$id': typeof AuthEmpleadosIdRoute
  '/pedidos/$idPedido': typeof AuthPedidosIdPedidoRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/caja': typeof AuthCajaRoute
  '/catalogo': typeof AuthCatalogoRoute
  '/cuentas-por-pagar': typeof AuthCuentasPorPagarRoute
  '/impresoras': typeof AuthImpresorasRoute
  '/inventario': typeof AuthInventarioRoute
  '/mesas': typeof AuthMesasRoute
  '/mi-nomina': typeof AuthMiNominaRoute
  '/nomina': typeof AuthNominaRoute
  '/panaderia': typeof AuthPanaderiaRoute
  '/traslados': typeof AuthTrasladosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/': typeof AuthIndexRoute
  '/cobro/$idPedido': typeof AuthCobroIdPedidoRoute
  '/empleados/$id': typeof AuthEmpleadosIdRoute
  '/pedidos/$idPedido': typeof AuthPedidosIdPedidoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/caja': typeof AuthCajaRoute
  '/_auth/catalogo': typeof AuthCatalogoRoute
  '/_auth/cuentas-por-pagar': typeof AuthCuentasPorPagarRoute
  '/_auth/impresoras': typeof AuthImpresorasRoute
  '/_auth/inventario': typeof AuthInventarioRoute
  '/_auth/mesas': typeof AuthMesasRoute
  '/_auth/mi-nomina': typeof AuthMiNominaRoute
  '/_auth/nomina': typeof AuthNominaRoute
  '/_auth/panaderia': typeof AuthPanaderiaRoute
  '/_auth/traslados': typeof AuthTrasladosRoute
  '/_auth/usuarios': typeof AuthUsuariosRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/cobro/$idPedido': typeof AuthCobroIdPedidoRoute
  '/_auth/empleados/$id': typeof AuthEmpleadosIdRoute
  '/_auth/pedidos/$idPedido': typeof AuthPedidosIdPedidoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/caja'
    | '/catalogo'
    | '/cuentas-por-pagar'
    | '/impresoras'
    | '/inventario'
    | '/mesas'
    | '/mi-nomina'
    | '/nomina'
    | '/panaderia'
    | '/traslados'
    | '/usuarios'
    | '/cobro/$idPedido'
    | '/empleados/$id'
    | '/pedidos/$idPedido'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/caja'
    | '/catalogo'
    | '/cuentas-por-pagar'
    | '/impresoras'
    | '/inventario'
    | '/mesas'
    | '/mi-nomina'
    | '/nomina'
    | '/panaderia'
    | '/traslados'
    | '/usuarios'
    | '/'
    | '/cobro/$idPedido'
    | '/empleados/$id'
    | '/pedidos/$idPedido'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/caja'
    | '/_auth/catalogo'
    | '/_auth/cuentas-por-pagar'
    | '/_auth/impresoras'
    | '/_auth/inventario'
    | '/_auth/mesas'
    | '/_auth/mi-nomina'
    | '/_auth/nomina'
    | '/_auth/panaderia'
    | '/_auth/traslados'
    | '/_auth/usuarios'
    | '/_auth/'
    | '/_auth/cobro/$idPedido'
    | '/_auth/empleados/$id'
    | '/_auth/pedidos/$idPedido'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/usuarios': {
      id: '/_auth/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthUsuariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/traslados': {
      id: '/_auth/traslados'
      path: '/traslados'
      fullPath: '/traslados'
      preLoaderRoute: typeof AuthTrasladosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/panaderia': {
      id: '/_auth/panaderia'
      path: '/panaderia'
      fullPath: '/panaderia'
      preLoaderRoute: typeof AuthPanaderiaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/nomina': {
      id: '/_auth/nomina'
      path: '/nomina'
      fullPath: '/nomina'
      preLoaderRoute: typeof AuthNominaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mi-nomina': {
      id: '/_auth/mi-nomina'
      path: '/mi-nomina'
      fullPath: '/mi-nomina'
      preLoaderRoute: typeof AuthMiNominaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mesas': {
      id: '/_auth/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthMesasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventario': {
      id: '/_auth/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthInventarioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/impresoras': {
      id: '/_auth/impresoras'
      path: '/impresoras'
      fullPath: '/impresoras'
      preLoaderRoute: typeof AuthImpresorasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cuentas-por-pagar': {
      id: '/_auth/cuentas-por-pagar'
      path: '/cuentas-por-pagar'
      fullPath: '/cuentas-por-pagar'
      preLoaderRoute: typeof AuthCuentasPorPagarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/catalogo': {
      id: '/_auth/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthCatalogoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/caja': {
      id: '/_auth/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthCajaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pedidos/$idPedido': {
      id: '/_auth/pedidos/$idPedido'
      path: '/pedidos/$idPedido'
      fullPath: '/pedidos/$idPedido'
      preLoaderRoute: typeof AuthPedidosIdPedidoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/empleados/$id': {
      id: '/_auth/empleados/$id'
      path: '/empleados/$id'
      fullPath: '/empleados/$id'
      preLoaderRoute: typeof AuthEmpleadosIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cobro/$idPedido': {
      id: '/_auth/cobro/$idPedido'
      path: '/cobro/$idPedido'
      fullPath: '/cobro/$idPedido'
      preLoaderRoute: typeof AuthCobroIdPedidoRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCajaRoute: typeof AuthCajaRoute
  AuthCatalogoRoute: typeof AuthCatalogoRoute
  AuthCuentasPorPagarRoute: typeof AuthCuentasPorPagarRoute
  AuthImpresorasRoute: typeof AuthImpresorasRoute
  AuthInventarioRoute: typeof AuthInventarioRoute
  AuthMesasRoute: typeof AuthMesasRoute
  AuthMiNominaRoute: typeof AuthMiNominaRoute
  AuthNominaRoute: typeof AuthNominaRoute
  AuthPanaderiaRoute: typeof AuthPanaderiaRoute
  AuthTrasladosRoute: typeof AuthTrasladosRoute
  AuthUsuariosRoute: typeof AuthUsuariosRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCobroIdPedidoRoute: typeof AuthCobroIdPedidoRoute
  AuthEmpleadosIdRoute: typeof AuthEmpleadosIdRoute
  AuthPedidosIdPedidoRoute: typeof AuthPedidosIdPedidoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCajaRoute: AuthCajaRoute,
  AuthCatalogoRoute: AuthCatalogoRoute,
  AuthCuentasPorPagarRoute: AuthCuentasPorPagarRoute,
  AuthImpresorasRoute: AuthImpresorasRoute,
  AuthInventarioRoute: AuthInventarioRoute,
  AuthMesasRoute: AuthMesasRoute,
  AuthMiNominaRoute: AuthMiNominaRoute,
  AuthNominaRoute: AuthNominaRoute,
  AuthPanaderiaRoute: AuthPanaderiaRoute,
  AuthTrasladosRoute: AuthTrasladosRoute,
  AuthUsuariosRoute: AuthUsuariosRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCobroIdPedidoRoute: AuthCobroIdPedidoRoute,
  AuthEmpleadosIdRoute: AuthEmpleadosIdRoute,
  AuthPedidosIdPedidoRoute: AuthPedidosIdPedidoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
